language: python
python:
  - '2.6'
  - '2.7'
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install requests[security]; fi
  - pip install -r requirements.txt
  - pip install coverage coveralls
before_script:
  - scripts/travis-setup.sh
script:
  - coverage run tests/fulltest.py
after_success:
  - coveralls
  - python scripts/show-memory.py
env:
  global:
    - secure: BNmMM2cK+CHIXA0Ij8kP3VGSDUFknRqdCiK7kc3SOb6RfHzrJ6kgPqXYDSDL1QcBc72NTaZ01KyJ6XGMNvxbSJuWLHyo90mXQBCWdTgvdTVSpQVifrD0oGbcEDSBmS7xaCLWLa+iUgx7Q0l/Ndwg7BNsczXJ3hK5JOs7DalUvIA=
    - secure: plQSBlLRnrkhL4TnSF8PM/bYD1ss1DBovfRS+/Ig2JFId0FOkzUFXRZDgeEhWiHQEa6sQxktiOcVr2vpMo9v+954ajP7c+h9jTcni9/9Sswm8+0oa0WuT/Dw8qoMa+lq64d+Zhoh7m7rh7VrpgnSu+OgJ0zOQ09J9cqFEapux+s=
    - SVNPARAMS="--no-auth-cache --non-interactive --quiet --username ${SVNUSER} --password ${SVNPASS}"
