language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
before_script:
  - mysql -uroot -e "create database playero;"
  - mysql -uroot playero < tests/res/playero.sql
  - printenv
  - echo $SVNUSER
script:
  - nosetests
