language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
before_script:
  - mysql -uroot -e "create database IF NOT EXISTS playero;"
  - mysql -uroot -e "CREATE USER 'myuser'@'127.0.0.1' IDENTIFIED BY PASSWORD 'mypass';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON playero.* TO 'myuser'@'%' WITH GRANT OPTION;"
  - mysql -uroot -e "FLUSH PRIVILEGES;"
  - mysql -umyuser -pmypass playero < tests/res/playero.sql
script:  nosetests
