language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
before_script:
  - mysql -uroot -e "create database playero;"
  - mysql -uroot playero < tests/res/playero.sql
  - svn --no-auth-cache --non-interactive --username $SVNUSER --password $SVNPASS --depth empty co svn://www.telenet.com.py/alterplayero/trunk@5 Playero
  - svn --no-auth-cache --non-interactive --username $SVNUSER --password $SVNPASS --set-depth infinity up -r 5 Playero/base
  - svn --no-auth-cache --non-interactive --username $SVNUSER --password $SVNPASS --set-depth infinity up -r 5 Playero/core
  - svn --no-auth-cache --non-interactive --username $SVNUSER --password $SVNPASS --set-depth infinity up -r 5 Playero/standard
  - svn --no-auth-cache --non-interactive --username $SVNUSER --password $SVNPASS --set-depth infinity up -r 5 Playero/settings
  - mv Playero/settings/settings.xml.example Playero/settings/settings.xml
script:
  - nosetests
